# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 07:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkinn', models.TimeField(blank=True, null=True)),
                ('checkout', models.TimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('late', models.TimeField(blank=True, null=True)),
                ('early', models.TimeField(blank=True, null=True)),
                ('total_time', models.TimeField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=200)),
                ('modified_by', models.DateField(blank=True, null=True)),
                ('modified_on', models.DateField(blank=True, null=True)),
                ('is_actve', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
