# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
