# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tracker', '0006_auto_20171018_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='early',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
