# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-21 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tracker', '0007_auto_20171018_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='total_time',
        ),
    ]
