# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-21 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tracker', '0008_remove_attendance_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='extended1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
