# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-08 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tracker', '0009_auto_20171021_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
